:api_key: 874de6cc085edbc48921817c6f582f55
:password: 0a72dee19f6d8f6445fda8fb4b5e7e8d
:theme_id: "49"
:preview_url: https://stesportes.commercesuite.com.br/loja/loja.php?loja=944848&opencode_theme=63b5c0398f79c
:debug: true
